name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: any
  # For Dio Kit
  dio: any
  flutter_ume: 0.2.1
  flutter_ume_kit_ui: 0.2.1
  flutter_ume_kit_perf: 0.2.1
  flutter_ume_kit_show_code: 0.2.1
  flutter_ume_kit_device: 0.2.1
  flutter_ume_kit_console: 0.2.1
  flutter_ume_kit_dio: 0.2.0
  flutter_resizeble_devices:
    path: ../kits/flutter_resizeble_devices

  shake_detector: ^0.1.1
  get_storage: ^2.1.1

dependency_overrides:
  vm_service: any
  flutter_ume:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_ume:
    path: ../
  flutter_ume_kit_ui:
    path: ../kits/flutter_ume_kit_ui
  flutter_ume_kit_perf:
    path: ../kits/flutter_ume_kit_perf
  flutter_ume_kit_show_code:
    path: ../kits/flutter_ume_kit_show_code
  flutter_ume_kit_device:
    path: ../kits/flutter_ume_kit_device
  flutter_ume_kit_console:
    path: ../kits/flutter_ume_kit_console
  flutter_ume_kit_dio:
    path: ../kits/flutter_ume_kit_dio
  flutter_ume_kit_channel_monitor:
    path: ../kits/flutter_ume_kit_channel_monitor
  
flutter:
  uses-material-design: true
