name: flutter_ume
description: UME is an in-app debug kits platform for Flutter apps. Fork by Nerdzlab.
version: 1.1.2
homepage: https://github.com/nerdzlab/flutter_ume_nerdzlab

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.5.2
  vm_service: ">=9.4.0 <15.0.0"
  tuple: ^2.0.2

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter
  melos: ^6.3.2
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
  lints: ^2.0.0

flutter:
  uses-material-design: true
