name: flutter_ume_kit_device
description: Device info kit for flutter_ume.
version: 1.0.0
homepage: https://github.com/nerdzlab/flutter_ume_nerdzlab

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/nerdzlab/flutter_ume_nerdzlab
  system_info2: any
  device_info_plus: any
  platform: any
  firebase_messaging: any
  get_storage: ^2.1.1
  shared_preferences: ^2.5.2
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
