name: flutter_ume_kit_console
description: Show debugPrint kit for flutter_ume.
version: 1.1.0
homepage: https://github.com/nerdzlab/flutter_ume_nerdzlab

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.2
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  flutter_ume:
    git:
      url: https://github.com/nerdzlab/flutter_ume_nerdzlab

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
