name: flutter_ume_kit_show_code
description: Show Code kit for flutter_ume.
version: 1.0.0
homepage: https://github.com/nerdzlab/flutter_ume_nerdzlab

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/nerdzlab/flutter_ume_nerdzlab
  share_plus: any
  vm_service: ^14.2.5
  string_scanner: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65

flutter:
